language: ruby

rvm:
  - 2.4.6
  - 2.5.5
  - 2.6.3  

cache:
  directories:
  - $HOME/nats-streaming-server

before_install:
  - bash ./scripts/install_server.sh

before_script:
  - export PATH=$HOME/nats-streaming-server:$PATH

sudo: required
dist: trusty
