language: ruby

rvm:
  - 2.3.6
  - 2.4.3
  - 2.5.0

cache:
  directories:
  - $HOME/nats-streaming-server

before_install:
  - bash ./scripts/install_server.sh

before_script:
  - export PATH=$HOME/nats-streaming-server:$PATH

sudo: required
dist: trusty
